---

- selinux:
    policy: targeted
    state: permissive

- name: Install packages for Apache
  yum:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - "httpd"
    - "mod_wsgi"

- name: Enables the Apache2 module "wsgi"
  apache2_module:
    state: present
    name: wsgi

- name: Copy httpd conf files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - info:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    - info:
      src: apache-conf/host.conf
      dest: /etc/httpd/conf.d/host.conf
    - info:
      src: apache-conf/rps.conf
      dest: /etc/httpd/conf.d/rps.conf
    - info:
      src: apache-conf/virtual-directory.conf
      dest: /etc/httpd/conf.d/virtual-directory.conf
  notify:
    - "restart httpd"

- name: Set symbolic links for file editing
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - info:
      src: /etc/httpd/conf.d/
      dest: /root/httpd-conf.d
    - info:
      src: /var/www/
      dest: /root/www

- name: Start the service and enable on startup
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - httpd
