---

- name: Install latest packages via pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools

- name: Install packages via pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - autopep8
    - docker-compose
    - docker-py
    - flake8
    - Flask
    - flask-simpleldap
    - gunicorn
    - pep8
    - prettytable
    - pylint
    - python-ceilometerclient
    - python-cinderclient
    - python-glanceclient
    - python-heatclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient
    - python-swiftclient
    - PyYAML
    - requests
    - shade
    - six
    - supervisor
    - virtualenv
