---

- name: Copy supervisord files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - info:
      src: "supervisord.service.j2"
      dest: "/etc/systemd/system/supervisord.service"
    - info:
      src: "supervisord.conf.j2"
      dest: "/etc/supervisord.conf"
  notify:
    - "restart supervisord"

- name: Start the service and enable on startup
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - supervisord
